### ISSUE TITLE
Multiple lists

### ISSUE THREAD

**Issue by jtagcat** [prologic/todo#18]
Because who likes to have a list per instance.

**Comment by prologic** [comment]
Yup makes sense and a whole new feature that we'll have to create a new data structure for. But shouldn't be that hard.

**Comment by jtagcat** [comment]
If there's plans to go bigger (multi-user), accounts might be a thing, though accounts in any simple app is a horrible thing to have.

**Comment by jtagcat** [comment]
Link (& cookie) based authentication..?

**Comment by jtagcat** [comment]
If user opens a link, it the list will be stored in the cookies, add a + icon in the list switcher, and somehow a - icon, what's not so easy to click and make it dynamically size.

**Comment by prologic** [comment]
> If there's plans to go bigger (multi-user), accounts might be a thing, though accounts in any simple app is a horrible thing to have.

I agree and its hard to do right and opens up many cans of worms :) I opted to leave multi-user features out of all the little self-hosted apps I've written thus far... That's not to say it shouldn't be added but maybe it can be done in such a way that you don't have to add it everywhere and make the same mistakes everywhere :)

**Comment by jtagcat** [comment]
Yeah, if any user lands at the front page, dump them to a new list.
Link based authentication is all fine. Asking for cookies permission could be in place of the list switcher, 'by clicking, you accept', a new list button acts as the accept button.
Can't immagine how removing lists would go.

..what distro do you use? :p

**Comment by prologic** [comment]
What you're suggesting short of drastically changes how the data is stored -- in a user's browser via cookies?

**Comment by prologic** [comment]
> ..what distro do you use? :p

long story; but used to use [CRUX](https://crux.nu] as a Desktop OS / Linux distro; but for the past few years primarily use a Macbook and macOS. Server-wise I still use CRUX, Proxmox and RancherOS

**Comment by jtagcat** [comment]
REEE CLICKABLE LINKS

**Comment by ocdtrekkie** [comment]
As a note, @jtagcat, if you want to check out my Sandstorm package of this app, it effectively solves this by default. Not to "promote" too far outside my own PR for it, but you can create as many grains (think files/documents, in a sense) of an app as you want which is basically a full instance of the app, and by default, each grain is only available to the user who creates it. You can then share the grain with other users (or create publicly accessible links).

Which is to say, that if you still look to create your own shell, it may be viable to leave multiple lists (and user authentication and sharing) entirely outside of the level of the app... and spawn multiple instances of the app, as Sandstorm already does for this application. That way, apps remain micro in scope, and don't have to each manage their own instantiation, authorization, security, etc.

**Comment by jtagcat** [comment]
I promised and didn't deliver, so I'm just watching this repo for my input and so on. You may treat me as a random acts of internet.

I use GitLab issues and Joplin for todos/notes atm.

**Comment by ocdtrekkie** [comment]
FWIW, I am also pretty much random acts of Internet. ;)

**Comment by prologic** [comment]
😀

**Comment by jtagcat** [comment]
(that should be a slightly horrified/terrified face, as random acts of internet have the tendency go poof, like me :upside_down_face:  ..though the upside that there are acts at all..)

**Comment by ocdtrekkie** [comment]
Heh, okay. But if you're ever interested in testing out Sandstorm and seeing how it compares to the vision you were working on last year, I'd be happy to set you up with an account on my box for you to play with.

**Comment by jtagcat** [comment]
lol, for me it wasn't a vision, it was a pot of many, many ideas..

I think it's still more practical to do many lists inside one instance, kind of like [etherpad](pad.k-space.ee/).

**Comment by ocdtrekkie** [comment]
Etherpad is actually one of the pre-installed apps on new Sandstorm servers! We actually package it in a single-document model, because it essentially guarantees Etherpad vulnerabilities can't be used to move from one document to another, and the shell/supervisor manages access to each document. (There is a writeup here https://sandstorm.io/how-it-works but the short version is that for the past six years, apps run in Sandstorm have been effectively impervious to most known CVEs in any functional sense. It *is* a very different model than most self-hosting solutions, we just argue it's better than the other ones.)

**Comment by jtagcat** [comment]
Nice point, but non-sandstorm users should feel nice as well. To accommodate Sandstorm, there should be a single-list flag available.

**Comment by prologic** [comment]
Guys sorry this is all great. Please submit whatever PRs you _think_ are good improvements to `prologic/todo`; I _wish_ I could be a bit more help (_after-all I did wrote it!_); however I'm a bit busy with another [project](https://github.com/prologic/twtxt) that's really picking up steam 😎

I will review / approve and merge any good PRs 👍

**Comment by ocdtrekkie** [comment]
@jtagcat That is definitely fair. It just seemed worth pointing out that the current implementation is particularly fantastic for my use case. ;)

@prologic I am meaning to look into TwTxt packaging too... it'll definitely be slightly harder because it entails network access. I may open an issue to inquire on the requirements.
