### ISSUE TITLE
Avoid auto-zoom on mobile Safari

### ISSUE THREAD

**Issue by ocdtrekkie** [prologic/todo#30]
So, fun fact I recently learned: If the input box font size is less than 16px (it is like 11px by default), mobile Safari on iOS will subtly zoom in when you click on said text box. This is really annoying if it's a todo app that puts it's action buttons on the side of the screen since it cuts them off. (I will upload a screenshot shortly.)

It's easy enough to literally inline the fix, but I don't know if you would be open to that or prefer to put it in an existing CSS file somewhere.

Sauces: https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone
and example fix https://github.com/zenhack/yata/commit/7a8815c79fa4b7b1d657c9ab05d7c0d4566989a8

**Comment by ocdtrekkie** [comment]
![image](https://user-images.githubusercontent.com/4399499/88320472-3e1dbc00-cce3-11ea-8e54-46c2703aaa42.png)

**Comment by prologic** [comment]
I _think_ you should wait for #27 :)

**Comment by KevinNThomas** [comment]
@ocdtrekkie Does this problem happen on the demo page here: https://2do-demo.page ? The demo here is what I'm working on getting imemented in https://github.com/prologic/todo/pull/27 so if the app on that demo page still has that problem, I can work on adding the fix in that PR.

**Comment by ocdtrekkie** [comment]
Yeah, same effect on your demo page, though since you put most of your buttons on the left in your theme its a tad less irritating.

**Comment by KevinNThomas** [comment]
Okay, this commit should fix it: https://github.com/prologic/todo/pull/27/commits/7870202b3f233db084638b670d9539c3fc6ed2f4. It sets `maximum-scale=1` which prevents the zooming from happening without messing with font sizes. The only downside seems to be it prevents pinch zooming on android devices, but I don't see too many cases where someone would want to zoom in, because the layout should be optimized enough to not require zooming to begin with. Curious as to what @prologic thinks.

**Comment by ocdtrekkie** [comment]
Let me know when I can test it.

**Comment by KevinNThomas** [comment]
@ocdtrekkie The change should be active at https://2do-demo.page/ now.

**Comment by ocdtrekkie** [comment]
I can confirm that's a fix!

**Comment by prologic** [comment]
Is there an open PR to fix this that I missed?

**Comment by KevinNThomas** [comment]
I made the commit to this PR: https://github.com/prologic/todo/pull/27 which I still need to modify to use the `flag` package.

**Comment by prologic** [comment]
Nice 👍

**Comment by KevinNThomas** [comment]
@ocdtrekkie Change has been merged in
