### ISSUE TITLE
Update demo page with new version

### ISSUE THREAD

**Issue by KevinNThomas** [prologic/todo#35]
The demo page at https://todo.mills.io/ should probably be updated to the newest version. This was already mentioned in https://github.com/prologic/todo/pull/28 but I figured I'd also make an issue for it so we can keep track of it.

**Comment by prologic** [comment]
I _assume_ master is good to build from and publish? If so I'll do this tonight.

**Comment by KevinNThomas** [comment]
Just did a local build of the master branch and it looks good to me!

**Comment by prologic** [comment]
I also updated https://todo.mills.io 🎉 Great work guys!
