### ISSUE TITLE
key/value size is invalid

### ISSUE THREAD

**Issue by prologic** [prologic/todo#36]
Guys I'm getting this from my updated instaince:

```#!console
$ dks logs -f todo_todo
todo_todo.1.fhgrgusbwpnn@dm2.mills.io    | 2020/08/14 14:20:26 key/value size is invalid
todo_todo.1.2i1tunznbvl9@dm2.mills.io    | 2020/08/14 14:20:33 key/value size is invalid
todo_todo.1.nxcx9u7yyjiw@dm2.mills.io    | 2020/08/14 14:20:40 key/value size is invalid
todo_todo.1.7jnt4qbe5jgh@dm2.mills.io    | 2020/08/14 14:20:19 key/value size is invalid
```

Any ideas what changed here to cause this?

**Comment by ocdtrekkie** [comment]
I made no changes to todo itself.

If you haven't updated it since Kevin started sending PRs, is it possible there was a change in Bitcask between 0.1.6 and 0.3.5 that may not have fully been accounted for? It's hard for me to imagine the style PR had much to do with key/value stuff.

**Comment by prologic** [comment]
Yeah there was by the looks and the database is not longe valid and as its just a demo instance I just nuked the database and started again.

Its working again now! :) Thanks for responding!
